name: Build documentation

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
  
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  
      - name: Install docfx
        run: |
          sudo apt-get -y update
          sudo apt-get -y install dotnet8
          dotnet tool update -g docfx
          
      - name: Build documentation
        run: |
          docfx docfx~/docfx.json
            
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: docs
          path: docfx~/_site
        
  publish-docs:
    if: github.ref == 'refs/heads/main' && github.repository == 'bdunderscore/ndmf'
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    concurrency:
      group: docs-publish
      cancel-in-progress: true
    needs: build-docs
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: docs
          path: docs

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5